clc; clear all; format longG

%% parameters
m = 1000; 
k = 900;

sigma = 0.01; % noise

noise_bound =5.54*sigma;

stopTh = 1e-10;

%% load shared problem data (generated by example.py)
% Run example.py first so that problem_data.mat exists.
% This ensures both implementations operate on identical inputs.
data = load('problem_data.mat');
X    = data.cloudA;   % 3×m source point cloud
Y    = data.cloudB;   % 3×m target point cloud
R_gt = data.R_gt;     % 3×3 ground-truth rotation
t_gt = data.t_gt;     % 3×1 ground-truth translation

%% run algorithms

% run MS-GNC-TLS
[mgnc.R, mgnc.t] = GNC_TLS_PointCloudRegistration(Y, X, noise_bound^2, stopTh, 1, 1);


% run GNC-IRLS0
epsilon = 1; beta = 0.8;

[IRLS0.R, IRLS0.t] = GNC_IRLS0_PointCloudRegistration(Y, X, epsilon, beta, noise_bound, stopTh);

%% print structured results (format matches example.py output for easy comparison)
fprintf('=== MS-GNC-TLS ===\n');
fprintf('R:\n');
fprintf('  %.15g  %.15g  %.15g\n', mgnc.R(1,:), mgnc.R(2,:), mgnc.R(3,:));
fprintf('t:\n');
fprintf('  %.15g  %.15g  %.15g\n', mgnc.t');
fprintf('Rotation error (deg):          %.15g\n', getAngularError(R_gt, mgnc.R));
fprintf('Translation relative error:    %.15g\n', norm(mgnc.t - t_gt) / norm(t_gt));

fprintf('\n');
fprintf('=== GNC-IRLS0 ===\n');
fprintf('R:\n');
fprintf('  %.15g  %.15g  %.15g\n', IRLS0.R(1,:), IRLS0.R(2,:), IRLS0.R(3,:));
fprintf('t:\n');
fprintf('  %.15g  %.15g  %.15g\n', IRLS0.t');
fprintf('Rotation error (deg):          %.15g\n', getAngularError(R_gt, IRLS0.R));
fprintf('Translation relative error:    %.15g\n', norm(IRLS0.t - t_gt) / norm(t_gt));


%% IMPLEMENTATION DETAILS

%% GNC-IRLS0
function [R_hat, t_hat] = GNC_IRLS0_PointCloudRegistration(Y, X, epsilon, beta, epsilon_min, stopTh)
% Y: 3xm
% X: 3xm
    [~, m] = size(X);
    weights = ones(1, m);
    
    pre_cost = inf;
    
    for i = 1:100
      [R_hat,t_hat] = LS_PointCloudRegistration(Y, X, weights);   

      D = Y - R_hat * X - t_hat;  

      residual = vecnorm(D);                         

      weights = 1./max(residual, epsilon);
      weights = weights.^2;
      
      cost = weights * (residual').^2;  
      
      cost_diff = abs(cost - pre_cost);

      if cost_diff <= stopTh 
          break;
      end
         
      epsilon = max(beta*epsilon^2, epsilon_min);    
      pre_cost = cost;
    end      
end



%% (MS-)GNC-TLS
function [R_hat, t_hat] = GNC_TLS_PointCloudRegistration(Y, X, noise_bound_squared, stopTh, majorize, superlinear)
    [~, m] = size(Y);
    
    weights = ones(1,m);
    
    pre_cost = inf;
         
    for i=1:100
        [R_hat, t_hat] = LS_PointCloudRegistration(Y, X, weights);  
        
        abs_residual = vecnorm(Y - R_hat*X - t_hat);

        squared_residual = abs_residual.^2;
        
        max_residual = max(squared_residual);
        
        if i == 1
            if majorize
                mu = max(1 / (5*max_residual/noise_bound_squared - 1), 1e-6);
            else
                mu = max(1 / (5*max_residual/noise_bound_squared - 1), 1e-6);
            end
        end
      
        if majorize
            [weights] = M_gncWeightsUpdate(weights, mu, squared_residual, noise_bound_squared);                         
        else
            [weights] = gncWeightsUpdate(weights, mu, squared_residual, noise_bound_squared);                         
        end
        
        cost = weights * squared_residual';   
              
        cost_diff = abs(cost - pre_cost);
        
        if cost_diff <= stopTh 
            break;
        end
   
        if superlinear
            if mu < 1
                mu = min(sqrt(mu) * 1.4, 1e16);
            else
                mu = min(mu * 1.4, 1e16);
            end
        else
            mu = min(mu * 1.4, 1e16);
        end
        pre_cost = cost;
    end
end

%% Other help functions
function rotError = getAngularError(R_gt,R_est)

rotError = abs(acos( (trace(R_gt' * R_est)-1) / 2 ));
rotError = rad2deg( rotError );
end

function [R, t] = LS_PointCloudRegistration(Y, X, weights)
    s = sum(weights);

    x = X * weights' / s;
    y = Y * weights' / s;

    X_ = X - x; Y_ = Y - y;

    sqrtw = sqrt(weights);
    R= LS_RotationSearch( sqrtw .* Y_, sqrtw .* X_);  

    t = y - R*x;
end

function [R_hat] = LS_RotationSearch(Y, X)
    % Y = R*X
    % Y: 3xm 
    % X: 3xm
    M = Y*X';

    [U, ~, V] = svd(M);

    D = diag([1,1, det(U)*det(V)]);

    R_hat = U*D*V';
end

function [weights] = M_gncWeightsUpdate(weights, mu, residuals, barc2)

    ub = (mu+1)^2/mu^2 * barc2;
    lb = barc2; % 

    for k = 1:length(residuals)
        if residuals(k) - ub >= 0
            weights(k) = 0;
        elseif residuals(k) - lb <= 0
            weights(k) = 1;
        else
            weights(k) = sqrt( barc2/residuals(k) )*(mu+1)  - mu;
        end
    end
end


function [weights, lb, ub] = gncWeightsUpdate(weights, mu, residuals, barc2)
ub = (mu+1)/mu * barc2;
lb = (mu)/(mu+1) * barc2; 

for k = 1:length(residuals)
    if residuals(k) - ub >= 0
        weights(k) = 0;
        
    elseif residuals(k) - lb <= 0
        weights(k) = 1;
        
    else                
        weights(k) = sqrt( barc2*mu*(mu+1)/residuals(k) ) - mu;
    end
end
end
